# Generated by Django 4.2.3 on 2023-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='in_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
