# Generated by Django 4.2.3 on 2023-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_in_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Pets', 'Pets'), ('Sport', 'Sport'), ('Other', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
