# Generated by Django 4.2.3 on 2023-11-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Pets', 'Pets'), ('Other', 'Other')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
