# Generated by Django 4.2.3 on 2023-11-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_category_alter_bid_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
