# Generated by Django 4.2.3 on 2023-11-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auctionlisting_starting_bid_delete_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='image_url',
            new_name='photo',
        ),
    ]
